spring:
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false

ribbon:
  eureka:
    enabled: false