management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# my laptop is slow... delay hystrix kick-in for local tests
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000