management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database: MYSQL

#logging:
#  level:
#    root: INFO
#    io:
#      pivotal: DEBUG
#    com:
#      netflix: OFF
#    org:
#      flywaydb: DEBUG
#        core.internal:
#          dbsupport.SqlScript: DEBUG # SQL only
#          command.DbMigrate: DEBUG
